apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-pdb
  namespace: webchat
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chat-pdb
  namespace: webchat
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: chat
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: messages-pdb
  namespace: webchat
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: messages
