global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ["gateway:4000"]
    metrics_path: /metrics

  - job_name: chat
    dns_sd_configs:
      - names: ["chat"]
        type: A
        port: 5000
    metrics_path: /metrics

  - job_name: messages
    static_configs:
      - targets: ["messages:3003"]
    metrics_path: /metrics

  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
